### ISSUE TITLE
Add "New" menu item to clear editor

### ISSUE THREAD

**Issue by lehnerpat** [smetzlaff/openDLX#10]
While the functionality is present, it's somewhat unintuitive to clear the Code Editor only by using the "Clear" button in the editor.

Programs with file editing usually offer a "New [file]" menu item which clears the editing area, any possible state and the path used for the "Save" menu item.

I think adding such a menu item would further improve usability.

**Comment by smetzlaff** [comment]
I've added this functionality, but no file will be associated to the editor content until the user assembles (which creates a temporary file) or saves the file. See 884f96d8b13f147f25be415a97b45f2070be0589.

I think that the assignment of a file at this stage is not needed in the simulator, since first it might be annoying to the user that just wants to write a short program and second it is a bit in contradiction to the used editor concept (which is not a real editor, since it has no capabilities for undo (& redo), does not show which file is currently edited, and the editor does not know if the current state is a saved state or not). However, this behaviour poses a bug: if a file is opened and then "new file" is triggered, the UI asks if the current file needs to be saved no matter if the file was changed or not.

It would be interesting to know how the users want to use the editor, i.e. is a full-blown editor needed or not?

**Comment by lehnerpat** [comment]
The "Save file?" prompt bug can "easily" be solved by a `modified` flag -- but catching all changes is something that needs to be done and tested. I think for the moment this functionality is already an improvement (and yes, not binding a filename to the new file is how I had intended it).

I think rudimentary features in the editor (such as undo/redo and cohorts) would be a very good idea, especially for beginner-level users, who need to assemble their code often to see how it works. That would save them the work of having to switch back and forth between the simulator and their own editor.  
But that is kind of beyond the scope of this issue.... maybe we should open a new one for this topic.
