### ISSUE TITLE
Structure of JMenuBar factory classes

### ISSUE THREAD

**Issue by lehnerpat** [smetzlaff/openDLX#13]
The project currently uses an abstract superclass `JMenuBarFactory` and its decendent `MainFrameMenuBarFactory`.

The factory needs to be instantiated (instead of providing its factory methods statically) and even saves some state about the created menu bar (though this is marked as "very dirty implementation").

I'd like to imlement a fix for this "very dirty" implementation, thereby removing the need for the static HashMaps which save the index of the menus and menu items.

To this end, I would change the signature of the `createJMenuBar()` method. But since it is overridden, I would also need to change it in the abstract class.

As there is currently only one subclass of `JMenuBarFactory`, I'd like to merge the two classes into one and do some other refactoring to improve the structure and readability of the whole factoring process.

I just wanted to ask if there are any plans for other windows or frames which need a `JMenuBarFactory` (i.e. are there any further subclasses of it planned) or is it fine for me to merge and refactor the two classes?

**Comment by smetzlaff** [comment]
I'm thinking about a menu or tool bar for the editor window (with features like undo, enable syntax highlighting, ...) for a future version. However, since I'm not sure how and when this will be realised, I cannot make a statement about the necessity of the `JMenuBarFactory` for now. Hence, I would say that the classes can be merged and for the case that the editor window is equipped with a menu bar I (or anyone else) could pull the overlapping methods into a new super class.

**Comment by smetzlaff** [comment]
The two HashMaps are currently needed to synchronise the state of the forwarding checkbox in the menu and the options dialogue. I was thinking about other ways for implementing this, but the other solutions that came to mind seemed to be to complicated (to much glue code and additional classes). So, I would appreciate any solution for that.
